/**
 * 389 Find the difference
 * Given two strings s and t which consist of only lowercase letters.

 * String t is generated by random shuffling string s and
 * then add one more letter at a random position.

 * Find the letter that was added in t.
 *
 */

 public class DifferenceString{
   public static void main(String[] args){
     String s1 = "abcd";
     String s2 = "abcdf";

     System.out.println("The added letter is " + differenceString(s1, s2));
   }

   public static char differenceString(String s, String t){
     int chars = 0;
     int chart = 0;
     //Convert the char to integer and sum all integers
     for(int i = 0; i < s.length(); i++)
        chars += (int)s.charAt(i);
     for(int j = 0; j < t.length(); j++)
        chart += (int)t.charAt(j);
      //Subtraction to compute the difference of two string and then convert it to char
     return (char)(chart - chars);
   }
 }
